apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-web
spec:
  selector:
    matchLabels:
      #TODO
  template:
    metadata:
      labels:
        app: numbers-web
    spec:
      containers:
        - name: web
          image: #TODO
          env:
            - name: RngApi__Url
              value: #TODO

