trigger:
 - main

pool:
  vmImage: 'ubuntu-latest'

steps:
 - task: PowerShell@2
   inputs:
    script: |
      az --version
      docker version
      kubectl version --client
      dotnet --list-sdks