apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
spec:
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
        - name: app
          image: courselabs/simple-web:6.0