apiVersion: v1
kind: Pod
metadata:
  name: simple-web
  labels:
    app: simple-web
spec:
  containers:
    - name: app
      image: courselabs/simple-web:6.0
      envFrom:
        - configMapRef:
            name: simple-web-config