apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api
spec:
  selector:
    matchLabels:
      app: numbers-api
  template:
    metadata:
      labels:
        app: numbers-api
    spec:
      containers:
        - name: api
          image: dotnetaz001.azurecr.io/rng/api:6.0
